camera_stream_slicer.h: drop default constructor to add C++20 support
C++20 removed support for aggregate initialization with an initializer list when a constructor is defined, even a `= default` one.

Otherwise fails with

sdk/modules/stream/cpp/src/camera_stream_slicer.cpp:105:53: error: cannot convert ‘<brace-enclosed initializer list>’ to ‘Metavision::Slice&&’
  105 |         const bool new_slice_added = queue_->emplace({status, t, nevents, curt_event_buffer_, curt_trigger_buffer_});